name: kibun
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  email_validator: 2.1.17
  cupertino_icons: 1.0.8
  provider: 6.1.2
  connectivity_plus: 5.0.2
  graphql_flutter: 5.2.0-beta.6
  flutter_secure_storage: 9.2.2
  device_info_plus: 10.1.0
  another_flushbar: 1.12.30

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
